#!/bin/bash
# Advanced auto-scaling configuration

# Thresholds
CPU_SCALE_UP=80
CPU_SCALE_DOWN=30
MEMORY_SCALE_UP=85
MEMORY_SCALE_DOWN=50
NETWORK_SCALE_UP=1000  # MB/s

# Limits
MIN_INSTANCES=2
MAX_INSTANCES=10

# Predictive scaling
PEAK_HOURS="09:00-18:00"
WEEKEND_SCALE_FACTOR=0.7
HOLIDAY_SCALE_FACTOR=0.5

# Monitoring intervals
METRIC_INTERVAL=5
SCALE_CHECK_INTERVAL=60

# Alert settings
ALERT_EMAIL="admin@example.com"
ALERT_THRESHOLD=3 