FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /build
RUN git clone https://github.com/mudler/LocalAGI.git .
RUN make build

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /build/# localagi removed /usr/local/bin/

EXPOSE 8080


# Run as non-root user
USER nobody
CMD ["# localagi removed", "--address", "0.0.0.0:8080", "--models-path", "/models"]
