FROM tabbyml/tabby:latest

ENV TABBY_MODEL=TabbyML/StarCoder-1B
ENV TABBY_DEVICE=cpu

EXPOSE 8080


# Run as non-root user
USER nobody
CMD ["serve", "--model", "${TABBY_MODEL}", "--device", "${TABBY_DEVICE}", "--no-webserver"]
