# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import neuromorphic_pb2 as neuromorphic__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in neuromorphic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeuromorphicEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSpikes = channel.unary_unary(
                '/neuromorphic.v1.NeuromorphicEngine/ProcessSpikes',
                request_serializer=neuromorphic__pb2.SpikeInput.SerializeToString,
                response_deserializer=neuromorphic__pb2.SpikeOutput.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/neuromorphic.v1.NeuromorphicEngine/TrainModel',
                request_serializer=neuromorphic__pb2.TrainingData.SerializeToString,
                response_deserializer=neuromorphic__pb2.TrainingResult.FromString,
                _registered_method=True)
        self.GetResourceUsage = channel.unary_unary(
                '/neuromorphic.v1.NeuromorphicEngine/GetResourceUsage',
                request_serializer=neuromorphic__pb2.ResourceQuery.SerializeToString,
                response_deserializer=neuromorphic__pb2.NeuroResourceUsage.FromString,
                _registered_method=True)


class NeuromorphicEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSpikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeuromorphicEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSpikes': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSpikes,
                    request_deserializer=neuromorphic__pb2.SpikeInput.FromString,
                    response_serializer=neuromorphic__pb2.SpikeOutput.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=neuromorphic__pb2.TrainingData.FromString,
                    response_serializer=neuromorphic__pb2.TrainingResult.SerializeToString,
            ),
            'GetResourceUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceUsage,
                    request_deserializer=neuromorphic__pb2.ResourceQuery.FromString,
                    response_serializer=neuromorphic__pb2.NeuroResourceUsage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neuromorphic.v1.NeuromorphicEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neuromorphic.v1.NeuromorphicEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NeuromorphicEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSpikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuromorphic.v1.NeuromorphicEngine/ProcessSpikes',
            neuromorphic__pb2.SpikeInput.SerializeToString,
            neuromorphic__pb2.SpikeOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuromorphic.v1.NeuromorphicEngine/TrainModel',
            neuromorphic__pb2.TrainingData.SerializeToString,
            neuromorphic__pb2.TrainingResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuromorphic.v1.NeuromorphicEngine/GetResourceUsage',
            neuromorphic__pb2.ResourceQuery.SerializeToString,
            neuromorphic__pb2.NeuroResourceUsage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
