# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neuromorphic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12neuromorphic.proto\x12\x0fneuromorphic.v1\"\xcd\x01\n\nSpikeInput\x12\x16\n\x0e\x65ncoded_spikes\x18\x01 \x01(\x0c\x12\x17\n\x0ftemporal_window\x18\x02 \x01(\r\x12\x16\n\x0eneuron_profile\x18\x03 \x01(\t\x12\x42\n\x0c\x63ontext_tags\x18\x04 \x03(\x0b\x32,.neuromorphic.v1.SpikeInput.ContextTagsEntry\x1a\x32\n\x10\x43ontextTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbc\x01\n\x0bSpikeOutput\x12\x17\n\x0b\x61\x63tivations\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x43\n\x0c\x65nergy_usage\x18\x02 \x03(\x0b\x32-.neuromorphic.v1.SpikeOutput.EnergyUsageEntry\x12\x1b\n\x13processing_metadata\x18\x03 \x01(\t\x1a\x32\n\x10\x45nergyUsageEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x85\x01\n\x0cTrainingData\x12,\n\x07samples\x18\x01 \x03(\x0b\x32\x1b.neuromorphic.v1.SpikeInput\x12-\n\x07targets\x18\x02 \x03(\x0b\x32\x1c.neuromorphic.v1.SpikeOutput\x12\x18\n\x10training_profile\x18\x03 \x01(\t\"m\n\x0eTrainingResult\x12\x0c\n\x04loss\x18\x01 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x02\x12;\n\x0eresources_used\x18\x03 \x01(\x0b\x32#.neuromorphic.v1.NeuroResourceUsage\"=\n\rResourceQuery\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12\x16\n\x0ehistory_window\x18\x02 \x01(\r\"m\n\x12NeuroResourceUsage\x12\x15\n\renergy_joules\x18\x01 \x01(\x02\x12\x17\n\x0f\x63ompute_seconds\x18\x02 \x01(\x02\x12\x11\n\tspike_ops\x18\x03 \x01(\r\x12\x14\n\x0cmemory_bytes\x18\x04 \x01(\r2\x8d\x02\n\x12NeuromorphicEngine\x12L\n\rProcessSpikes\x12\x1b.neuromorphic.v1.SpikeInput\x1a\x1c.neuromorphic.v1.SpikeOutput\"\x00\x12N\n\nTrainModel\x12\x1d.neuromorphic.v1.TrainingData\x1a\x1f.neuromorphic.v1.TrainingResult\"\x00\x12Y\n\x10GetResourceUsage\x12\x1e.neuromorphic.v1.ResourceQuery\x1a#.neuromorphic.v1.NeuroResourceUsage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neuromorphic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPIKEINPUT_CONTEXTTAGSENTRY']._options = None
  _globals['_SPIKEINPUT_CONTEXTTAGSENTRY']._serialized_options = b'8\001'
  _globals['_SPIKEOUTPUT_ENERGYUSAGEENTRY']._options = None
  _globals['_SPIKEOUTPUT_ENERGYUSAGEENTRY']._serialized_options = b'8\001'
  _globals['_SPIKEOUTPUT'].fields_by_name['activations']._options = None
  _globals['_SPIKEOUTPUT'].fields_by_name['activations']._serialized_options = b'\020\001'
  _globals['_SPIKEINPUT']._serialized_start=40
  _globals['_SPIKEINPUT']._serialized_end=245
  _globals['_SPIKEINPUT_CONTEXTTAGSENTRY']._serialized_start=195
  _globals['_SPIKEINPUT_CONTEXTTAGSENTRY']._serialized_end=245
  _globals['_SPIKEOUTPUT']._serialized_start=248
  _globals['_SPIKEOUTPUT']._serialized_end=436
  _globals['_SPIKEOUTPUT_ENERGYUSAGEENTRY']._serialized_start=386
  _globals['_SPIKEOUTPUT_ENERGYUSAGEENTRY']._serialized_end=436
  _globals['_TRAININGDATA']._serialized_start=439
  _globals['_TRAININGDATA']._serialized_end=572
  _globals['_TRAININGRESULT']._serialized_start=574
  _globals['_TRAININGRESULT']._serialized_end=683
  _globals['_RESOURCEQUERY']._serialized_start=685
  _globals['_RESOURCEQUERY']._serialized_end=746
  _globals['_NEURORESOURCEUSAGE']._serialized_start=748
  _globals['_NEURORESOURCEUSAGE']._serialized_end=857
  _globals['_NEUROMORPHICENGINE']._serialized_start=860
  _globals['_NEUROMORPHICENGINE']._serialized_end=1129
# @@protoc_insertion_point(module_scope)
