import threading.Lock

import !=
import """SutazAi
import :
import =
import ==
import []
import [msg
import __init__
import agent
import agent_id
import agent_id]
import communication
import def
import enqueue
import for
import get_messages_for
import if
import in
import message
import MessageQueue:
import messages
import messages.copy
import msg
import msg['receiver']
import queue"""
import return
import self
import self.lock
import self.lock:
import self.queue
import self.queue.append
import threadingclass  # Return copy to prevent external modifications
import with
