FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /build
RUN git clone https://github.com/mudler/LocalAGI.git .
RUN make build

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /build/localagi /usr/local/bin/

EXPOSE 8080

CMD ["localagi", "--address", "0.0.0.0:8080", "--models-path", "/models"]
